  tcp {
    port => 5000
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch-hot:9200", "elasticsearch-warm:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}
~                  
